[2025-06-23T18:55:42.849+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_data_from_wiki manual__2025-06-23T18:55:32.727328+00:00 [queued]>
[2025-06-23T18:55:42.857+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_data_from_wiki manual__2025-06-23T18:55:32.727328+00:00 [queued]>
[2025-06-23T18:55:42.858+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-23T18:55:42.868+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): transform_data_from_wiki> on 2025-06-23 18:55:32.727328+00:00
[2025-06-23T18:55:42.872+0000] {standard_task_runner.py:57} INFO - Started process 167 to run task
[2025-06-23T18:55:42.876+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_data_from_wiki', 'manual__2025-06-23T18:55:32.727328+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp06bu84qr']
[2025-06-23T18:55:42.878+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask transform_data_from_wiki
[2025-06-23T18:55:42.939+0000] {task_command.py:410} INFO - Running <TaskInstance: wikipedia_flow.transform_data_from_wiki manual__2025-06-23T18:55:32.727328+00:00 [running]> on host bf870bd52d42
[2025-06-23T18:55:43.014+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rahul' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_data_from_wiki' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T18:55:32.727328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T18:55:32.727328+00:00'
[2025-06-23T18:55:43.015+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 81, in transform_wikidata_data
    data = kwargs["ti"].xcom_pull(key="data", task_id="extract_wikidata")
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2025-06-23T18:55:43.027+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_data_from_wiki, execution_date=20250623T185532, start_date=20250623T185542, end_date=20250623T185543
[2025-06-23T18:55:43.037+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task transform_data_from_wiki (xcom_pull() got an unexpected keyword argument 'task_id'; 167)
[2025-06-23T18:55:43.048+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-06-23T18:55:43.070+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
